const abilityImages = [
    "branch/0000.png",
    "branch/0000a.png",
    "branch/0001.png",
    "branch/0002.png",
    "branch/0010.png",
    "branch/0011.png",
    "branch/0020.png",
    "branch/0022.png",
    "branch/0100.png",
    "branch/0101.png",
    "branch/0110.png",
    "branch/0111.png",
    "branch/0200.png",
    "branch/0202.png",
    "branch/0220.png",
    "branch/0222.png",
    "branch/1000.png",
    "branch/1001.png",
    "branch/1010.png",
    "branch/1011.png",
    "branch/1100.png",
    "branch/1101.png",
    "branch/1110.png",
    "branch/1111.png",
    "branch/2000.png",
    "branch/2002.png",
    "branch/2020.png",
    "branch/2022.png",
    "branch/2200.png",
    "branch/2202.png",
    "branch/2220.png",
    "branch/2222.png",
    "item/archer.png",
    "item/assassin.png",
    "item/mage.png",
    "item/shaman.png",
    "item/warrior.png",
    "icons/archer.png",
    "icons/assassin.png",
    "icons/mage.png",
    "icons/shaman.png",
    "icons/w.png",
    "icons/warrior.png",
    "node/archer.png",
    "node/archer_active.png",
    "node/archer_error.png",
    "node/archer_open.png",
    "node/assassin.png",
    "node/assassin_active.png",
    "node/assassin_error.png",
    "node/assassin_open.png",
    "node/blue.png",
    "node/blue_active.png",
    "node/blue_blocked.png",
    "node/blue_error.png",
    "node/blue_open.png",
    "node/mage.png",
    "node/mage_active.png",
    "node/mage_error.png",
    "node/mage_open.png",
    "node/magenta.png",
    "node/magenta_active.png",
    "node/magenta_blocked.png",
    "node/magenta_error.png",
    "node/magenta_open.png",
    "node/purple.png",
    "node/purple_active.png",
    "node/purple_blocked.png",
    "node/purple_error.png",
    "node/purple_open.png",
    "node/red.png",
    "node/red_active.png",
    "node/red_blocked.png",
    "node/red_error.png",
    "node/red_open.png",
    "node/shaman.png",
    "node/shaman_active.png",
    "node/shaman_error.png",
    "node/shaman_open.png",
    "node/warrior.png",
    "node/warrior_active.png",
    "node/warrior_error.png",
    "node/warrior_open.png",
    "node/white.png",
    "node/white_active.png",
    "node/white_blocked.png",
    "node/white_error.png",
    "node/white_open.png",
    "node/yellow.png",
    "node/yellow_active.png",
    "node/yellow_blocked.png",
    "node/yellow_error.png",
    "node/yellow_open.png",
    "aspect/archer.png",
    "aspect/assassin.png",
    "aspect/mage.png",
    "aspect/shaman.png",
    "aspect/warrior.png",
];

async function preLoadAssets() {
    const preloadImage = src =>
        new Promise((resolve, reject) => {
            const image = new Image();
            image.onload = resolve;
            image.onerror = reject;
            image.src = src;
        });

// Preload an image
//     await preloadImage('https://picsum.photos/100/100');

    const prefix = "./img/";
// Preload a bunch of images in parallel 
    await Promise.all(abilityImages.map(x => preloadImage(prefix + x)));
}