name: Update personal website with changes.

on:
  push:
    branches: [main]

jobs:
  SFTP-Deploy-Action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vite site
        run: npm run build

      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}

          local-path: dist/ # compiled output
          remote-path: /wynnsmith
          remote-port: 22
