export const orderedBaseStats = [
    "baseHealth",
    "",
    "baseEarthDefence",
    "baseThunderDefence",
    "baseFireDefence",
    "baseWaterDefence",
    "baseAirDefence",
    "",
    "baseDamage",
    "baseEarthDamage",
    "baseThunderDamage",
    "baseWaterDamage",
    "baseFireDamage",
    "baseAirDamage",
] as const;

export const orderedSkillPointIds = ["rawStrength", "rawDexterity", "rawIntelligence", "rawDefence", "rawAgility"] as const;

export const orderedRegularIds = [
    "rawAttackSpeed", // the single most important stat
    "",
    "rawHealth", // Health
    "healthRegenRaw",
    "healthRegen",
    "healingEfficiency",
    "lifeSteal",
    "manaRegen", // Mana
    "manaSteal",
    "rawMaxMana",
    "exploding", // nonsense
    "poison",
    "thorns",
    "reflection",
    "stealing",
    "knockback",
    "mainAttackRange",
    "walkSpeed", // Movement
    "jumpHeight",
    "sprint",
    "sprintRegen",
    "gatherSpeed", // extreme nonsense
    "gatherXpBonus",
    "lootBonus",
    "lootQuality",
    "xpBonus",
    "weakenEnemy", // enemy debuffs
    "slowEnemy",
    "", // Ele-defs
    "earthDefence",
    "thunderDefence",
    "waterDefence",
    "fireDefence",
    "airDefence",
    "elementalDefence",
    "",
    // Damage
    "rawDamage",
    "rawMainAttackDamage",
    "rawSpellDamage",
    "rawNeutralDamage",
    "rawNeutralMainAttackDamage",
    "rawNeutralSpellDamage",
    "rawElementalDamage",
    "rawElementalMainAttackDamage",
    "rawElementalSpellDamage",
    "rawEarthDamage",
    "rawEarthMainAttackDamage",
    "rawEarthSpellDamage",
    "rawThunderDamage",
    "rawThunderMainAttackDamage",
    "rawThunderSpellDamage",
    "rawWaterDamage",
    "rawWaterMainAttackDamage",
    "rawWaterSpellDamage",
    "rawFireDamage",
    "rawFireMainAttackDamage",
    "rawFireSpellDamage",
    "rawAirDamage",
    "rawAirMainAttackDamage",
    "rawAirSpellDamage",
    "damage",
    "spellDamage",
    "mainAttackDamage",
    "neutralDamage",
    "neutralMainAttackDamage",
    "neutralSpellDamage",
    "elementalDamage",
    "elementalMainAttackDamage",
    "elementalSpellDamage",
    "earthDamage",
    "earthMainAttackDamage",
    "earthSpellDamage",
    "thunderDamage",
    "thunderMainAttackDamage",
    "thunderSpellDamage",
    "waterDamage",
    "waterMainAttackDamage",
    "waterSpellDamage",
    "fireDamage",
    "fireMainAttackDamage",
    "fireSpellDamage",
    "airDamage",
    "airMainAttackDamage",
    "airSpellDamage",
    "criticalDamageBonus",
    "", // Spell Costs
    "1stSpellCost",
    "2ndSpellCost",
    "3rdSpellCost",
    "4thSpellCost",
    "raw1stSpellCost",
    "raw2ndSpellCost",
    "raw3rdSpellCost",
    "raw4thSpellCost",
] as const;

// TODO: remove the symbols from the name, (while keeping the color split between ex. "Neutral" and "Damage")
export const base_stats = {
    "baseHealth": {name: "§4⚔ Health", color:"health", symbol: "health"},
    "baseEarthDefence": {name: "§2✤ Earth§7 Defence", color:"earth", symbol: "earth"},
    "baseThunderDefence": {name: "§e✦ Thunder§7 Defence", color:"thunder", symbol: "thunder"},
    "baseWaterDefence": {name: "§b❉ Water§7 Defence", color:"water", symbol: "water"},
    "baseFireDefence": {name: "§c✹ Fire§7 Defence", color:"fire", symbol: "fire"},
    "baseAirDefence": {name: "§f❋ Air§7 Defence", color:"air", symbol: "air"},

    "baseDamage": {name: "§6✣ Neutral§7 Damage", color:"neutral", symbol: "neutral"},
    "baseEarthDamage": {name: "§2✤ Earth§7 Damage", color:"earth", symbol: "earth"},
    "baseThunderDamage": {name: "§e✦ Thunder§7 Damage", color:"thunder", symbol: "thunder"},
    "baseWaterDamage": {name: "§b❉ Water§7 Damage", color:"water", symbol: "water"},
    "baseFireDamage": {name: "§c✹ Fire§7 Damage", color:"fire", symbol: "fire"},
    "baseAirDamage": {name: "§f❋ Air§7 Damage", color:"air", symbol: "air"},
} as const;

export const identifications = {
    // Skill Points
    "rawStrength": {name: "Strength", color: "earth"},
    "rawDexterity": {name: "Dexterity", color: "thunder"},
    "rawIntelligence": {name: "Intelligence", color: "water"},
    "rawDefence": {name: "Defence", color: "fire"},
    "rawAgility": {name: "Agility", color: "air"},
    // Raw Damage
    "rawDamage": {name: "Raw Damage"},
    "rawMainAttackDamage": {name: "Raw Main Attack Damage"},
    "rawSpellDamage": {name: "Raw Spell Damage"},
    "rawNeutralDamage": {name: "Raw Neutral Damage"},
    "rawNeutralMainAttackDamage": {name: "Raw Neutral Main Attack Damage"},
    "rawNeutralSpellDamage": {name: "Raw Neutral Spell Damage"},
    "rawElementalDamage": {name: "Raw Elemental Damage"},
    "rawElementalMainAttackDamage": {name: "Raw Elemental Main Attack Damage"},
    "rawElementalSpellDamage": {name: "Raw Elemental Spell Damage"},
    "rawEarthDamage": {name: "Raw Earth Damage"},
    "rawEarthMainAttackDamage": {name: "Raw Earth Main Attack Damage"},
    "rawEarthSpellDamage": {name: "Raw Earth Spell Damage"},
    "rawThunderDamage": {name: "Raw Thunder Damage"},
    "rawThunderMainAttackDamage": {name: "Raw Thunder Main Attack Damage"},
    "rawThunderSpellDamage": {name: "Raw Thunder Spell Damage"},
    "rawWaterDamage": {name: "Raw Water Damage"},
    "rawWaterMainAttackDamage": {name: "Raw Water Main Attack Damage"},
    "rawWaterSpellDamage": {name: "Raw Water Spell Damage"},
    "rawFireDamage": {name: "Raw Fire Damage"},
    "rawFireMainAttackDamage": {name: "Raw Fire Main Attack Damage"},
    "rawFireSpellDamage": {name: "Raw Fire Spell Damage"},
    "rawAirDamage": {name: "Raw Air Damage"},
    "rawAirMainAttackDamage": {name: "Raw Air Main Attack Damage"},
    "rawAirSpellDamage": {name: "Raw Air Spell Damage"},
    // % Damage
    "damage": {name: "Damage %", suffix: "%"},
    "spellDamage": {name: "Spell Damage %", suffix: "%"},
    "mainAttackDamage": {name: "Main Attack Damage %", suffix: "%"},
    "neutralDamage": {name: "Neutral Damage %", suffix: "%"},
    "neutralMainAttackDamage": {name: "Neutral Main Attack Damage %", suffix: "%"},
    "neutralSpellDamage": {name: "Neutral Spell Damage %", suffix: "%"},
    "elementalDamage": {name: "Elemental Damage %", suffix: "%"},
    "elementalMainAttackDamage": {name: "Elemental Spell Damage %", suffix: "%"},
    "elementalSpellDamage": {name: "Elemental Spell Damage %", suffix: "%"},
    "earthDamage": {name: "Earth Damage %", suffix: "%"},
    "earthMainAttackDamage": {name: "Earth Main Attack Damage %", suffix: "%"},
    "earthSpellDamage": {name: "Earth Spell Damage %", suffix: "%"},
    "thunderDamage": {name: "Thunder Damage %", suffix: "%"},
    "thunderMainAttackDamage": {name: "Thunder Main Attack Damage %", suffix: "%"},
    "thunderSpellDamage": {name: "Thunder Spell Damage %", suffix: "%"},
    "waterDamage": {name: "Water Damage %", suffix: "%"},
    "waterMainAttackDamage": {name: "Water Main Attack Damage %", suffix: "%"},
    "waterSpellDamage": {name: "Water Spell Damage %", suffix: "%"},
    "fireDamage": {name: "Fire Damage %", suffix: "%"},
    "fireMainAttackDamage": {name: "Fire Main Attack Damage %", suffix: "%"},
    "fireSpellDamage": {name: "Fire Spell Damage %", suffix: "%"},
    "airDamage": {name: "Air Damage %", suffix: "%"},
    "airMainAttackDamage": {name: "Air Main Attack Damage %", suffix: "%"},
    "airSpellDamage": {name: "Air Spell Damage %", suffix: "%"},
    // Passive Damage
    "exploding": {name: "Exploding", suffix: "%"},
    "poison": {name: "Poison", suffix: "/3s"},
    "thorns": {name: "Thorns", suffix: "%"},
    "reflection": {name: "Reflection", suffix: "%"},
    // Other Damage
    "criticalDamageBonus": {name: "Critical Damage Bonus", suffix: "%"},
    "knockback": {name: "Knockback %"},
    "mainAttackRange": {name: "Main Attack Range", suffix: "%"},
    "rawAttackSpeed": {name: "Attack Speed", suffix: " tier"},
    // Health
    "rawHealth": {name: "Health"},
    "healingEfficiency": {name: "Healing Efficiency", suffix: "%"},
    "healthRegenRaw": {name: "Health Regen"},
    "healthRegen": {name: "Health Regen %", suffix: "%"},
    // Mana
    "rawMaxMana": {name: "Max Mana"},
    "manaRegen": {name: "Mana Regen", suffix: "/5s"},
    // Steals
    "lifeSteal": {name: "Life Steal", suffix: "/3s"},
    "manaSteal": {name: "Mana Steal", suffix: "/3s"},
    // Costs
    "1stSpellCost": {name: "1st Spell Cost %", suffix: "%", invert: "true"},
    "2ndSpellCost": {name: "2nd Spell Cost %", suffix: "%", invert: "true"},
    "3rdSpellCost": {name: "3rd Spell Cost %", suffix: "%", invert: "true"},
    "4thSpellCost": {name: "4th Spell Cost %", suffix: "%", invert: "true"},
    "raw1stSpellCost": {name: "1st Spell Cost", invert: "true"},
    "raw2ndSpellCost": {name: "2nd Spell Cost", invert: "true"},
    "raw3rdSpellCost": {name: "3rd Spell Cost", invert: "true"},
    "raw4thSpellCost": {name: "4th Spell Cost", invert: "true"},
    // Movement
    "walkSpeed": {name: "Walk Speed %", suffix: "%"},
    "jumpHeight": {name: "jump Height"},
    "sprint": {name: "Sprint", suffix: "%"},
    "sprintRegen": {name: "Sprint Regen", suffix: "%"},
    // XP and Gathering
    "gatherSpeed": {name: "Gather Speed", suffix: "%"},
    "gatherXpBonus": {name: "Gather XP Bonus", suffix: "%"},
    "lootBonus": {name: "Loot Bonus", suffix: "%"},
    "lootQuality": {name: "Loot Quality", suffix: "%"},
    "stealing": {name: "Stealing", suffix: "%"},
    "xpBonus": {name: "Combat XP Bonus", suffix: "%"},
    // Debuffs
    "weakenEnemy": {name: "Weaken Enemy", suffix: "%"},
    "slowEnemy": {name: "Slow Enemy", suffix: "%"},
    // Ele-def %
    "earthDefence": {name: "Earth Defence %", suffix: "%"},
    "thunderDefence": {name: "Thunder Defence %", suffix: "%"},
    "waterDefence": {name: "Water Defence %", suffix: "%"},
    "fireDefence": {name: "Fire Defence %", suffix: "%"},
    "airDefence": {name: "Air Defence %", suffix: "%"},
    "elementalDefence": {name: "Elemental Defence %", suffix: "%"},
} as const;
